# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Wed Jan 31 17:04:29 2018
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 720)
        MainWindow.setMinimumSize(QtCore.QSize(960, 720))
        MainWindow.setMaximumSize(QtCore.QSize(960, 720))
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 960, 720))
        self.label.setMinimumSize(QtCore.QSize(960, 720))
        self.label.setMaximumSize(QtCore.QSize(960, 720))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("Bild0.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_1 = QtGui.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 86, 20, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.doubleSpinBox_sensor1_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor1_temperature.setGeometry(QtCore.QRect(281, 113, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor1_temperature.setFont(font)
        self.doubleSpinBox_sensor1_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor1_temperature.setFrame(False)
        self.doubleSpinBox_sensor1_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor1_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor1_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor1_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor1_temperature"))
        self.doubleSpinBox_flowBronkhorst = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_flowBronkhorst.setGeometry(QtCore.QRect(100, 138, 91, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_flowBronkhorst.setFont(font)
        self.doubleSpinBox_flowBronkhorst.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_flowBronkhorst.setFrame(False)
        self.doubleSpinBox_flowBronkhorst.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_flowBronkhorst.setMaximum(25.01)
        self.doubleSpinBox_flowBronkhorst.setSingleStep(0.01)
        self.doubleSpinBox_flowBronkhorst.setProperty("value", 10.01)
        self.doubleSpinBox_flowBronkhorst.setObjectName(_fromUtf8("doubleSpinBox_flowBronkhorst"))
        self.doubleSpinBox_set_flowFesto = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_set_flowFesto.setEnabled(False)
        self.doubleSpinBox_set_flowFesto.setGeometry(QtCore.QRect(250, 300, 121, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_set_flowFesto.setFont(font)
        self.doubleSpinBox_set_flowFesto.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.doubleSpinBox_set_flowFesto.setFrame(True)
        self.doubleSpinBox_set_flowFesto.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_set_flowFesto.setDecimals(2)
        self.doubleSpinBox_set_flowFesto.setMaximum(10.0)
        self.doubleSpinBox_set_flowFesto.setSingleStep(0.5)
        self.doubleSpinBox_set_flowFesto.setProperty("value", 10.0)
        self.doubleSpinBox_set_flowFesto.setObjectName(_fromUtf8("doubleSpinBox_set_flowFesto"))
        self.doubleSpinBox_flowFesto = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_flowFesto.setEnabled(False)
        self.doubleSpinBox_flowFesto.setGeometry(QtCore.QRect(252, 364, 91, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_flowFesto.setFont(font)
        self.doubleSpinBox_flowFesto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_flowFesto.setFrame(False)
        self.doubleSpinBox_flowFesto.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_flowFesto.setMaximum(10.01)
        self.doubleSpinBox_flowFesto.setSingleStep(0.01)
        self.doubleSpinBox_flowFesto.setProperty("value", 10.01)
        self.doubleSpinBox_flowFesto.setObjectName(_fromUtf8("doubleSpinBox_flowFesto"))
        self.doubleSpinBox_optidew_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_optidew_temperature.setGeometry(QtCore.QRect(50, 300, 70, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_optidew_temperature.setFont(font)
        self.doubleSpinBox_optidew_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_optidew_temperature.setFrame(False)
        self.doubleSpinBox_optidew_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_optidew_temperature.setSingleStep(0.01)
        self.doubleSpinBox_optidew_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_optidew_temperature.setObjectName(_fromUtf8("doubleSpinBox_optidew_temperature"))
        self.doubleSpinBox_optidew_humidity = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_optidew_humidity.setGeometry(QtCore.QRect(50, 330, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_optidew_humidity.setFont(font)
        self.doubleSpinBox_optidew_humidity.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_optidew_humidity.setFrame(False)
        self.doubleSpinBox_optidew_humidity.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_optidew_humidity.setMaximum(100.0)
        self.doubleSpinBox_optidew_humidity.setSingleStep(0.01)
        self.doubleSpinBox_optidew_humidity.setProperty("value", 99.99)
        self.doubleSpinBox_optidew_humidity.setObjectName(_fromUtf8("doubleSpinBox_optidew_humidity"))
        self.doubleSpinBox_dg4_humidity1 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_dg4_humidity1.setGeometry(QtCore.QRect(720, 368, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_dg4_humidity1.setFont(font)
        self.doubleSpinBox_dg4_humidity1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_dg4_humidity1.setFrame(False)
        self.doubleSpinBox_dg4_humidity1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_dg4_humidity1.setMaximum(100.0)
        self.doubleSpinBox_dg4_humidity1.setSingleStep(0.01)
        self.doubleSpinBox_dg4_humidity1.setProperty("value", 99.99)
        self.doubleSpinBox_dg4_humidity1.setObjectName(_fromUtf8("doubleSpinBox_dg4_humidity1"))
        self.doubleSpinBox_dg4_set_humidity = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_dg4_set_humidity.setGeometry(QtCore.QRect(796, 398, 91, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_dg4_set_humidity.setFont(font)
        self.doubleSpinBox_dg4_set_humidity.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.doubleSpinBox_dg4_set_humidity.setFrame(True)
        self.doubleSpinBox_dg4_set_humidity.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_dg4_set_humidity.setDecimals(2)
        self.doubleSpinBox_dg4_set_humidity.setMaximum(100.0)
        self.doubleSpinBox_dg4_set_humidity.setSingleStep(1.0)
        self.doubleSpinBox_dg4_set_humidity.setProperty("value", 99.99)
        self.doubleSpinBox_dg4_set_humidity.setObjectName(_fromUtf8("doubleSpinBox_dg4_set_humidity"))
        self.doubleSpinBox_dg4_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_dg4_temperature.setGeometry(QtCore.QRect(720, 428, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_dg4_temperature.setFont(font)
        self.doubleSpinBox_dg4_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_dg4_temperature.setFrame(False)
        self.doubleSpinBox_dg4_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_dg4_temperature.setSingleStep(0.01)
        self.doubleSpinBox_dg4_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_dg4_temperature.setObjectName(_fromUtf8("doubleSpinBox_dg4_temperature"))
        self.doubleSpinBox_dg4_humidity2 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_dg4_humidity2.setGeometry(QtCore.QRect(720, 398, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_dg4_humidity2.setFont(font)
        self.doubleSpinBox_dg4_humidity2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_dg4_humidity2.setFrame(False)
        self.doubleSpinBox_dg4_humidity2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_dg4_humidity2.setMaximum(100.0)
        self.doubleSpinBox_dg4_humidity2.setSingleStep(0.01)
        self.doubleSpinBox_dg4_humidity2.setProperty("value", 99.99)
        self.doubleSpinBox_dg4_humidity2.setObjectName(_fromUtf8("doubleSpinBox_dg4_humidity2"))
        self.doubleSpinBox_sensor2_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor2_temperature.setGeometry(QtCore.QRect(358, 180, 70, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor2_temperature.setFont(font)
        self.doubleSpinBox_sensor2_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor2_temperature.setFrame(False)
        self.doubleSpinBox_sensor2_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor2_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor2_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor2_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor2_temperature"))
        self.doubleSpinBox_sensor3_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor3_temperature.setGeometry(QtCore.QRect(445, 180, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor3_temperature.setFont(font)
        self.doubleSpinBox_sensor3_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor3_temperature.setFrame(False)
        self.doubleSpinBox_sensor3_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor3_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor3_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor3_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor3_temperature"))
        self.doubleSpinBox_sensor4_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor4_temperature.setGeometry(QtCore.QRect(531, 180, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor4_temperature.setFont(font)
        self.doubleSpinBox_sensor4_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor4_temperature.setFrame(False)
        self.doubleSpinBox_sensor4_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor4_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor4_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor4_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor4_temperature"))
        self.doubleSpinBox_sensor5_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor5_temperature.setGeometry(QtCore.QRect(619, 180, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor5_temperature.setFont(font)
        self.doubleSpinBox_sensor5_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor5_temperature.setFrame(False)
        self.doubleSpinBox_sensor5_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor5_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor5_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor5_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor5_temperature"))
        self.doubleSpinBox_sensor6_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor6_temperature.setGeometry(QtCore.QRect(705, 180, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor6_temperature.setFont(font)
        self.doubleSpinBox_sensor6_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor6_temperature.setFrame(False)
        self.doubleSpinBox_sensor6_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor6_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor6_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor6_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor6_temperature"))
        self.doubleSpinBox_sensor7_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor7_temperature.setGeometry(QtCore.QRect(790, 180, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor7_temperature.setFont(font)
        self.doubleSpinBox_sensor7_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor7_temperature.setFrame(False)
        self.doubleSpinBox_sensor7_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor7_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor7_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor7_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor7_temperature"))
        self.doubleSpinBox_sensor8_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sensor8_temperature.setGeometry(QtCore.QRect(666, 495, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sensor8_temperature.setFont(font)
        self.doubleSpinBox_sensor8_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sensor8_temperature.setFrame(False)
        self.doubleSpinBox_sensor8_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sensor8_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sensor8_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sensor8_temperature.setObjectName(_fromUtf8("doubleSpinBox_sensor8_temperature"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(94, 111, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(253, 341, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(723, 312, 20, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(861, 312, 10, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 291, 40, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 280, 60, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.doubleSpinBox_set_setpointBronkhorst = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_set_setpointBronkhorst.setGeometry(QtCore.QRect(96, 42, 121, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_set_setpointBronkhorst.setFont(font)
        self.doubleSpinBox_set_setpointBronkhorst.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.doubleSpinBox_set_setpointBronkhorst.setFrame(True)
        self.doubleSpinBox_set_setpointBronkhorst.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_set_setpointBronkhorst.setDecimals(2)
        self.doubleSpinBox_set_setpointBronkhorst.setMaximum(25.0)
        self.doubleSpinBox_set_setpointBronkhorst.setSingleStep(0.5)
        self.doubleSpinBox_set_setpointBronkhorst.setProperty("value", 5.0)
        self.doubleSpinBox_set_setpointBronkhorst.setObjectName(_fromUtf8("doubleSpinBox_set_setpointBronkhorst"))
        self.doubleSpinBox_setpointBronkhorst = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_setpointBronkhorst.setGeometry(QtCore.QRect(99, 69, 91, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_setpointBronkhorst.setFont(font)
        self.doubleSpinBox_setpointBronkhorst.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_setpointBronkhorst.setFrame(False)
        self.doubleSpinBox_setpointBronkhorst.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_setpointBronkhorst.setMaximum(25.01)
        self.doubleSpinBox_setpointBronkhorst.setSingleStep(0.01)
        self.doubleSpinBox_setpointBronkhorst.setProperty("value", 10.01)
        self.doubleSpinBox_setpointBronkhorst.setObjectName(_fromUtf8("doubleSpinBox_setpointBronkhorst"))
        self.doubleSpinBox_optidew_dewpoint = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_optidew_dewpoint.setGeometry(QtCore.QRect(50, 360, 80, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_optidew_dewpoint.setFont(font)
        self.doubleSpinBox_optidew_dewpoint.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_optidew_dewpoint.setFrame(False)
        self.doubleSpinBox_optidew_dewpoint.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_optidew_dewpoint.setMinimum(-100.0)
        self.doubleSpinBox_optidew_dewpoint.setMaximum(100.0)
        self.doubleSpinBox_optidew_dewpoint.setSingleStep(0.01)
        self.doubleSpinBox_optidew_dewpoint.setProperty("value", -23.75)
        self.doubleSpinBox_optidew_dewpoint.setObjectName(_fromUtf8("doubleSpinBox_optidew_dewpoint"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 303, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 334, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 362, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.doubleSpinBox_sht75_temperature = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_temperature.setGeometry(QtCore.QRect(179, 421, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_temperature.setFont(font)
        self.doubleSpinBox_sht75_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_temperature.setFrame(False)
        self.doubleSpinBox_sht75_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_temperature.setSingleStep(0.01)
        self.doubleSpinBox_sht75_temperature.setProperty("value", 23.75)
        self.doubleSpinBox_sht75_temperature.setObjectName(_fromUtf8("doubleSpinBox_sht75_temperature"))
        self.doubleSpinBox_sht75_temperature_1 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_temperature_1.setGeometry(QtCore.QRect(337, 422, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_temperature_1.setFont(font)
        self.doubleSpinBox_sht75_temperature_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_temperature_1.setFrame(False)
        self.doubleSpinBox_sht75_temperature_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_temperature_1.setSingleStep(0.01)
        self.doubleSpinBox_sht75_temperature_1.setProperty("value", 23.75)
        self.doubleSpinBox_sht75_temperature_1.setObjectName(_fromUtf8("doubleSpinBox_sht75_temperature_1"))
        self.doubleSpinBox_sht75_temperature_2 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_temperature_2.setGeometry(QtCore.QRect(178, 622, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_temperature_2.setFont(font)
        self.doubleSpinBox_sht75_temperature_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_temperature_2.setFrame(False)
        self.doubleSpinBox_sht75_temperature_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_temperature_2.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_sht75_temperature_2.setSingleStep(0.01)
        self.doubleSpinBox_sht75_temperature_2.setProperty("value", 23.75)
        self.doubleSpinBox_sht75_temperature_2.setObjectName(_fromUtf8("doubleSpinBox_sht75_temperature_2"))
        self.doubleSpinBox_sht75_temperature_3 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_temperature_3.setGeometry(QtCore.QRect(337, 623, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_temperature_3.setFont(font)
        self.doubleSpinBox_sht75_temperature_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_temperature_3.setFrame(False)
        self.doubleSpinBox_sht75_temperature_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_temperature_3.setSingleStep(0.01)
        self.doubleSpinBox_sht75_temperature_3.setProperty("value", 23.75)
        self.doubleSpinBox_sht75_temperature_3.setObjectName(_fromUtf8("doubleSpinBox_sht75_temperature_3"))
        self.doubleSpinBox_sht75_humidity = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_humidity.setGeometry(QtCore.QRect(178, 442, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_humidity.setFont(font)
        self.doubleSpinBox_sht75_humidity.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_humidity.setFrame(False)
        self.doubleSpinBox_sht75_humidity.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_humidity.setMaximum(100.0)
        self.doubleSpinBox_sht75_humidity.setSingleStep(0.01)
        self.doubleSpinBox_sht75_humidity.setProperty("value", 99.99)
        self.doubleSpinBox_sht75_humidity.setObjectName(_fromUtf8("doubleSpinBox_sht75_humidity"))
        self.doubleSpinBox_sht75_humidity_1 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_humidity_1.setGeometry(QtCore.QRect(337, 442, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_humidity_1.setFont(font)
        self.doubleSpinBox_sht75_humidity_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_humidity_1.setFrame(False)
        self.doubleSpinBox_sht75_humidity_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_humidity_1.setMaximum(100.0)
        self.doubleSpinBox_sht75_humidity_1.setSingleStep(0.01)
        self.doubleSpinBox_sht75_humidity_1.setProperty("value", 99.99)
        self.doubleSpinBox_sht75_humidity_1.setObjectName(_fromUtf8("doubleSpinBox_sht75_humidity_1"))
        self.doubleSpinBox_sht75_humidity_2 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_humidity_2.setGeometry(QtCore.QRect(177, 644, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_humidity_2.setFont(font)
        self.doubleSpinBox_sht75_humidity_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_humidity_2.setFrame(False)
        self.doubleSpinBox_sht75_humidity_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_humidity_2.setMaximum(100.0)
        self.doubleSpinBox_sht75_humidity_2.setSingleStep(0.01)
        self.doubleSpinBox_sht75_humidity_2.setProperty("value", 99.99)
        self.doubleSpinBox_sht75_humidity_2.setObjectName(_fromUtf8("doubleSpinBox_sht75_humidity_2"))
        self.doubleSpinBox_sht75_humidity_3 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sht75_humidity_3.setGeometry(QtCore.QRect(337, 645, 81, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_sht75_humidity_3.setFont(font)
        self.doubleSpinBox_sht75_humidity_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_sht75_humidity_3.setFrame(False)
        self.doubleSpinBox_sht75_humidity_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sht75_humidity_3.setMaximum(100.0)
        self.doubleSpinBox_sht75_humidity_3.setSingleStep(0.01)
        self.doubleSpinBox_sht75_humidity_3.setProperty("value", 99.99)
        self.doubleSpinBox_sht75_humidity_3.setObjectName(_fromUtf8("doubleSpinBox_sht75_humidity_3"))
        self.label_warning_humidity = QtGui.QLabel(self.centralwidget)
        self.label_warning_humidity.setGeometry(QtCore.QRect(530, 590, 411, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.label_warning_humidity.setFont(font)
        self.label_warning_humidity.setObjectName(_fromUtf8("label_warning_humidity"))
        self.label_warning_flow = QtGui.QLabel(self.centralwidget)
        self.label_warning_flow.setGeometry(QtCore.QRect(530, 650, 411, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.label_warning_flow.setFont(font)
        self.label_warning_flow.setObjectName(_fromUtf8("label_warning_flow"))
        self.label_sensor1 = QtGui.QLabel(self.centralwidget)
        self.label_sensor1.setGeometry(QtCore.QRect(354, 205, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor1.setFont(font)
        self.label_sensor1.setObjectName(_fromUtf8("label_sensor1"))
        self.label_sensor2 = QtGui.QLabel(self.centralwidget)
        self.label_sensor2.setGeometry(QtCore.QRect(442, 205, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor2.setFont(font)
        self.label_sensor2.setObjectName(_fromUtf8("label_sensor2"))
        self.label_sensor3 = QtGui.QLabel(self.centralwidget)
        self.label_sensor3.setGeometry(QtCore.QRect(530, 205, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor3.setFont(font)
        self.label_sensor3.setObjectName(_fromUtf8("label_sensor3"))
        self.label_sensor4 = QtGui.QLabel(self.centralwidget)
        self.label_sensor4.setGeometry(QtCore.QRect(616, 205, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor4.setFont(font)
        self.label_sensor4.setObjectName(_fromUtf8("label_sensor4"))
        self.label_sensor5 = QtGui.QLabel(self.centralwidget)
        self.label_sensor5.setGeometry(QtCore.QRect(702, 204, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor5.setFont(font)
        self.label_sensor5.setObjectName(_fromUtf8("label_sensor5"))
        self.label_sensor6 = QtGui.QLabel(self.centralwidget)
        self.label_sensor6.setGeometry(QtCore.QRect(788, 204, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor6.setFont(font)
        self.label_sensor6.setObjectName(_fromUtf8("label_sensor6"))
        self.label_sensor7 = QtGui.QLabel(self.centralwidget)
        self.label_sensor7.setGeometry(QtCore.QRect(278, 140, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor7.setFont(font)
        self.label_sensor7.setObjectName(_fromUtf8("label_sensor7"))
        self.label_sensor8 = QtGui.QLabel(self.centralwidget)
        self.label_sensor8.setGeometry(QtCore.QRect(666, 520, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor8.setFont(font)
        self.label_sensor8.setObjectName(_fromUtf8("label_sensor8"))
        self.label_sensorSHT1 = QtGui.QLabel(self.centralwidget)
        self.label_sensorSHT1.setGeometry(QtCore.QRect(177, 474, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensorSHT1.setFont(font)
        self.label_sensorSHT1.setObjectName(_fromUtf8("label_sensorSHT1"))
        self.label_sensorSHT2 = QtGui.QLabel(self.centralwidget)
        self.label_sensorSHT2.setGeometry(QtCore.QRect(337, 473, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensorSHT2.setFont(font)
        self.label_sensorSHT2.setObjectName(_fromUtf8("label_sensorSHT2"))
        self.label_sensorSHT3 = QtGui.QLabel(self.centralwidget)
        self.label_sensorSHT3.setGeometry(QtCore.QRect(176, 671, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensorSHT3.setFont(font)
        self.label_sensorSHT3.setObjectName(_fromUtf8("label_sensorSHT3"))
        self.label_sensorSHT4 = QtGui.QLabel(self.centralwidget)
        self.label_sensorSHT4.setGeometry(QtCore.QRect(337, 671, 81, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        self.label_sensorSHT4.setFont(font)
        self.label_sensorSHT4.setObjectName(_fromUtf8("label_sensorSHT4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Humidity and Temperature control", None))
        self.label_1.setText(_translate("MainWindow", "Air", None))
        self.doubleSpinBox_sensor1_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_flowBronkhorst.setSuffix(_translate("MainWindow", " l/min", None))
        self.doubleSpinBox_set_flowFesto.setSuffix(_translate("MainWindow", " l/min", None))
        self.doubleSpinBox_flowFesto.setSuffix(_translate("MainWindow", " l/min", None))
        self.doubleSpinBox_optidew_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_optidew_humidity.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_dg4_humidity1.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_dg4_set_humidity.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_dg4_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_dg4_humidity2.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_sensor2_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sensor3_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sensor4_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sensor5_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sensor6_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sensor7_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sensor8_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.label_2.setText(_translate("MainWindow", "Bronk", None))
        self.label_3.setText(_translate("MainWindow", "Festo", None))
        self.label_4.setText(_translate("MainWindow", "Out", None))
        self.label_5.setText(_translate("MainWindow", "In", None))
        self.label_6.setText(_translate("MainWindow", "DG-4", None))
        self.label_7.setText(_translate("MainWindow", "Optidew", None))
        self.doubleSpinBox_set_setpointBronkhorst.setSuffix(_translate("MainWindow", " l/min", None))
        self.doubleSpinBox_setpointBronkhorst.setSuffix(_translate("MainWindow", " l/min", None))
        self.doubleSpinBox_optidew_dewpoint.setSuffix(_translate("MainWindow", " °C", None))
        self.label_8.setText(_translate("MainWindow", "Temp", None))
        self.label_9.setText(_translate("MainWindow", "Hum", None))
        self.label_10.setText(_translate("MainWindow", "D.p.", None))
        self.doubleSpinBox_sht75_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sht75_temperature_1.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sht75_temperature_2.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sht75_temperature_3.setSuffix(_translate("MainWindow", " °C", None))
        self.doubleSpinBox_sht75_humidity.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_sht75_humidity_1.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_sht75_humidity_2.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_sht75_humidity_3.setSuffix(_translate("MainWindow", "%", None))
        self.label_warning_humidity.setText(_translate("MainWindow", "<html><head/><body><p>Humidity is LOW!!!</p></body></html>", None))
        self.label_warning_flow.setText(_translate("MainWindow", "<html><head/><body><p>Flow is LOW!!!</p></body></html>", None))
        self.label_sensor1.setText(_translate("MainWindow", "Sensor N1", None))
        self.label_sensor2.setText(_translate("MainWindow", "Sensor N2", None))
        self.label_sensor3.setText(_translate("MainWindow", "Sensor N3", None))
        self.label_sensor4.setText(_translate("MainWindow", "Sensor N4", None))
        self.label_sensor5.setText(_translate("MainWindow", "Sensor N5", None))
        self.label_sensor6.setText(_translate("MainWindow", "Sensor N6", None))
        self.label_sensor7.setText(_translate("MainWindow", "Sensor N7", None))
        self.label_sensor8.setText(_translate("MainWindow", "Sensor N8", None))
        self.label_sensorSHT1.setText(_translate("MainWindow", "Sensor N1", None))
        self.label_sensorSHT2.setText(_translate("MainWindow", "Sensor N2", None))
        self.label_sensorSHT3.setText(_translate("MainWindow", "Sensor N3", None))
        self.label_sensorSHT4.setText(_translate("MainWindow", "Sensor N4", None))

